@startuml validacionInicial

title validacionInicial

actor Usuario
participant Tablero
participant IllegalArgumentException

Usuario -> Tablero: new Tablero(listaHexagonos, listaNumeros)
activate Tablero

Tablero -> Tablero: validarCantidadHexagonosYNumeros()
alt Cantidades válidas
    Tablero -> Tablero: asignarCoordenadasHexagonos()
    Tablero -> Tablero: asignarNumeroALosHexagonos()
    Tablero -> Tablero: inicializarVertices()
    Tablero -> Tablero: asignarAdyacentesAVertices()
else Cantidades inválidas
    create IllegalArgumentException
    Tablero -> IllegalArgumentException: new IllegalArgumentException()
end

deactivate Tablero
@enduml

